apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello.fullname" . }}
  labels:
    {{- include "hello.labels" . | nindent 4 }}
stringData:
  allowed: '"true"'
  enemies: aliens
  lives: "3"
