apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-1
  namespace: default
  labels:
    id: test
data:
  allowed: '"true"'
  enemies: aliens
  lives: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-2
  namespace: default
  labels:
    id: test
data:
  allowed: '"true"'
  enemies: aliens
  lives: "3"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-3
  namespace: default
  labels:
    id: test
data:
  allowed: '"true"'
  enemies: aliens
  lives: "3"
